name: CI

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker compose build

      - name: Set env
        run: echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV

      - name: Start services
        run: docker compose up -d

      - name: Wait a bit for DB
        run: sleep 10

      - name: Check running containers
        run: docker ps

      - name: Run logs (debug)
        run: docker compose logs

      - name: Run monitor once
        run: docker compose exec -T app python monitor.py
