name: CI

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker compose build

      - name: Check containers
        run: docker ps

      - name: Run logs
        run: docker compose logs

      - name: Run monitor
        run: docker compose run --rm app python monitor.py

      - name: Check database contents
        run: |
          docker compose exec -T db psql -U postgres -d monitor -c "SELECT * FROM checks;"
